[mongo]
host = 'localhost'
port = 27017
username = 'username'
password = 'password'
authSource = 'admin'
database = 'character_ai'
collections.character = 'character'

[postgres]
host = '172.27.96.1'
port = 5432
username = 'postgres'
password = 'postgres'
database = 'CharacterAI'

[zhipuai]
api_key = ''

[fastapi]
host = 'localhost'
port = 8000
