[mongo]
host = 'localhost'
port = 27017
username = 'username'
password = 'password'
authSource = 'admin'
database = 'character_ai'
collections.character = 'character'

[postgres]
host = 'localhost'
port = 5432
username = 'root'
password = 'password'
database = 'database'

[zhipuai]
api_key = ''

[fastapi]
host = 'localhost'
port = 8000
