# 2024/5/10
# zhangzhong

services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      # all set to default so you could just type
      # psql -h localhost to connent
      - POSTGRES_USER=zhangzhong
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=zhangzhong

  minio:
    image: bitnami/minio
    container_name: minio
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=root
      # Make sure that the environment variables MINIO_ROOT_PASSWORD and MINIO_SERVER_SECRET_KEY meet the 8 character minimum length requirement enforced by MinIO(R).
      - MINIO_ROOT_PASSWORD=12345678
