[postgres]
host = 'localhost'
port = 5432
username = 'ysukeg'
password = 'postgres'
database = 'characterai'

[zhipuai]
api_key = ''

[fastapi]
host = 'localhost'
port = 8000

[minio]
endpoint = 'localhost:9000'
access_key = 'root'
secret_key = '12345678'
secure = false
bucket_name = 'test'

[admin]
username = 'admin'
password = 'admin'

[qdrant]
host = 'localhost'
collection_name = 'my_collections'
prefer_grpc = false

[llm]
glm2_url = 'http://localhost:8086/character_llm'
glm3_url = 'http://localhost:8001/v1/chat/completions'